# Generated by Django 4.1.2 on 2022-10-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTypes',
            fields=[
                ('expensesbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses_app.expensesbasemodel')),
                ('type_name', models.CharField(max_length=255)),
                ('is_state', models.IntegerField(default=0)),
            ],
            bases=('expenses_app.expensesbasemodel',),
        ),
        migrations.CreateModel(
            name='PaymentTypes',
            fields=[
                ('expensesbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses_app.expensesbasemodel')),
                ('payment_name', models.CharField(max_length=255)),
                ('is_state', models.IntegerField(default=0)),
            ],
            bases=('expenses_app.expensesbasemodel',),
        ),
        migrations.CreateModel(
            name='SubTypes',
            fields=[
                ('expensesbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses_app.expensesbasemodel')),
                ('name', models.CharField(max_length=255)),
                ('is_state', models.IntegerField(default=0)),
                ('master_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_app.expensetypes')),
            ],
            bases=('expenses_app.expensesbasemodel',),
        ),
        migrations.CreateModel(
            name='PaymentTransactions',
            fields=[
                ('expensesbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses_app.expensesbasemodel')),
                ('flag', models.IntegerField(default=0)),
                ('amount', models.FloatField()),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_app.paymenttypes')),
            ],
            bases=('expenses_app.expensesbasemodel',),
        ),
    ]
